---
- name: Copy over Prometheus configuration
  template:
    src: prometheus.json.j2
    dest: /etc/prometheus/file_sd/{{ inventory_hostname }}.json
    mode: 0644
    owner: prometheus
    group: prometheus

- name: Copy over Blackbox Exporter configuration
  template:
    src: blackbox.json.j2
    dest: /etc/prometheus/file_sd/blackbox_{ inventory_hostname }}.json
    mode: 0644
    owner: prometheus
    group: prometheus
