---

- name: Common playbook
  hosts: all
  gather_facts: true
  become: no
  remote_user: root

  tasks:
  - name: Generating locales
    community.general.locale_gen:
      name: "{{ item }}"
    with_items:
      - en_US.UTF-8
      - ru_RU.UTF-8
  
  - name: Set default locale
    command: localectl set-locale LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_NUMERIC=en_US.UTF-8 LANGUAGE=en_US

  - name: Updating system
    ansible.builtin.apt:
      update_cache: yes
      upgrade: yes
      dpkg_options: 'force-confold,force-confdef'

  - name: Unconditionally reboot the machine with all defaults
    ansible.builtin.reboot:

  - name: Install lynis suggestions
    ansible.builtin.apt:
      dpkg_options: 'force-confold,force-confdef'
      pkg:
      - rkhunter
      - libpam-tmpdir
      - apt-listchanges
      - fail2ban
